### ISSUE TITLE
Global !global

### ISSUE THREAD

**Issue by NinjaBunny9000** [NinjaBunny9000/DeepThonk#34]
A global counter that uses globals to track mentions of uses of globals in code Bun's working on.

`!global` increments counter of how many times someone has pointed out that Bun's using globals
`!global torch <user>` passes the `!global` global torch counter to another user (preventing dupe counts)

Would be cool to be able to track how many per stream.
 - Testable with `!streamstart` & `!streamend` functions?
  - Might need to make these for testing other functions, regardless.

**Comment by BarePotato** [comment]
your wheels are square trying to travel a triangle road
